{% set name = "jscatter" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jscatter-{{ version }}.tar.gz
  sha256: c13855bbb0c0d9597c2a971fef9ea54384a8194c055a76e59cd3f8611c789e92

build:
  skip: true  # [py<39]
  script:
    # Remove cython generated files to re-generate them for numpy v1
    - {{ PYTHON }} -c "import pathlib; [p.with_suffix('.c').unlink() for p in pathlib.Path('.').rglob('*.pyx')]"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # gfortran called from setup.py but not currently used to build an extension
    - gfortran  # [win]
  host:
    - python
    - setuptools >=67.0
    - cmake >=3.26
    - wheel
    - cython >=3.0
    - numpy >=1.26.4
    - pip
  run:
    - python
    - scipy >=1.10
    - matplotlib-base >=3
    - pillow >=8.1
    - mdanalysis >=2.4.0
    - netcdf4
    - cython
    - fabio
    - pdb2pqr
    - requests
    - nglview
    - emcee
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - jscatter
    # Compiled extensions
    - jscatter.libs.cubature._cubature
    - jscatter.libs.cubature._test_integrands
    - jscatter.libs.surface

about:
  summary: Combines dataArrays with attributes for fitting plotting and analysis including models for Xray and neutron scattering
  license: GPL-3.0-or-later
  license_file: src/jscatter/LICENSE
  home: https://gitlab.com/biehl/jscatter
  doc_url: https://jscatter.readthedocs.io
  dev_url: https://gitlab.com/biehl/jscatter/

extra:
  recipe-maintainers:
    - t20100
