{% set name = "jscatter" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jscatter-{{ version }}.tar.gz
  sha256: 230dfde1943e6d639ba170e9b1bc74c97c69b707b7659cb463b459d451d14e04
  patches:
    - patches/0001-Add-PyMODINIT_FUNC.patch

build:
  skip: true  # [py<38]
  script:
    # Remove compiled *.pyd files
    - {{ PYTHON }} -c "import pathlib; [p.unlink() for p in pathlib.Path('.').rglob('*.pyd')]"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=67.0
    - cmake >=3.26
    - wheel
    - cython >=3.0
    - numpy >=1.21
    - pip
  run:
    - python
    - cmake >=3.26
    - numpydoc >=1.5
    - scipy >=1.8
    - matplotlib-base >=3
    - pillow >=8.1
    - mdanalysis >=2.4.0
    - cython
    - fabio
    - pdb2pqr
    - requests
    - nglview
    - emcee
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - jscatter

about:
  summary: Combines dataArrays with attributes for fitting plotting and analysis including models for Xray and neutron scattering
  license: GPL-3.0-or-later
  license_file: src/jscatter/LICENSE
  home: https://gitlab.com/biehl/jscatter
  doc_url: https://jscatter.readthedocs.io
  dev_url: https://gitlab.com/biehl/jscatter/

extra:
  recipe-maintainers:
    - t20100
